# Generated by Django 5.1.6 on 2025-03-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('skills', models.CharField(blank=True, max_length=60, null=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.CharField(blank=True, max_length=60, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='Projectimg')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='Projectimg')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='Projectimg')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
