# Generated by Django 5.1.6 on 2025-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoApp', '0002_skill_alter_projectdb_date_alter_projectdb_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdb',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='projectdb',
            name='skills',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
